name: Static analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpstan:
    name: PHPStan
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: phpstan:2.0.3, cs2pr

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: PHPStan
        run: phpstan analyze --no-progress --error-format=checkstyle --level=5 | cs2pr

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: php-cs-fixer:3.65.0, cs2pr

      - name: PHP-CS-Fixer
        run: php-cs-fixer --no-interaction --dry-run --format=checkstyle fix src | cs2pr

  psalm:
    name: Psalm
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none
          tools: vimeo/psalm:5.26.1

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Psalm
        run: psalm --no-progress --output-format=github